/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto;

import java.io.IOException;

/**
 *
 * @author Daniel
 */
public class PANEL extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PANEL.class.getName());

    /**
     * Creates new form PANEL
     */
    public PANEL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelVerde = new javax.swing.JPanel();
        BtnAdiDoc = new javax.swing.JButton();
        BtnListarEst = new javax.swing.JButton();
        BtnListarDoc = new javax.swing.JButton();
        BtnAdiEst = new javax.swing.JButton();
        PanelAmarillo = new javax.swing.JPanel();
        EntradaDeDatos = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        SalidaDeDatos = new javax.swing.JTextArea();
        LabelIngreso = new javax.swing.JLabel();
        LabelSalida = new javax.swing.JLabel();
        PanelAzul = new javax.swing.JPanel();
        LabelTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelVerde.setBackground(new java.awt.Color(204, 255, 204));

        BtnAdiDoc.setBackground(new java.awt.Color(0, 0, 0));
        BtnAdiDoc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnAdiDoc.setForeground(new java.awt.Color(255, 255, 255));
        BtnAdiDoc.setText("Adicionar Docente");
        BtnAdiDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdiDocActionPerformed(evt);
            }
        });

        BtnListarEst.setBackground(new java.awt.Color(0, 0, 0));
        BtnListarEst.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnListarEst.setForeground(new java.awt.Color(255, 255, 255));
        BtnListarEst.setText("Listar Estudiante");
        BtnListarEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListarEstActionPerformed(evt);
            }
        });

        BtnListarDoc.setBackground(new java.awt.Color(0, 0, 0));
        BtnListarDoc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnListarDoc.setForeground(new java.awt.Color(255, 255, 255));
        BtnListarDoc.setText("Listar Docente");
        BtnListarDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListarDocActionPerformed(evt);
            }
        });

        BtnAdiEst.setBackground(new java.awt.Color(0, 0, 0));
        BtnAdiEst.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnAdiEst.setForeground(new java.awt.Color(255, 255, 255));
        BtnAdiEst.setText("Adicionar Estudiante");
        BtnAdiEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdiEstActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelVerdeLayout = new javax.swing.GroupLayout(PanelVerde);
        PanelVerde.setLayout(PanelVerdeLayout);
        PanelVerdeLayout.setHorizontalGroup(
            PanelVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelVerdeLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(PanelVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnAdiEst, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnListarDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnListarEst, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAdiDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );
        PanelVerdeLayout.setVerticalGroup(
            PanelVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVerdeLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(BtnAdiEst, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(BtnAdiDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(BtnListarEst, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(BtnListarDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelAmarillo.setBackground(new java.awt.Color(255, 255, 204));

        EntradaDeDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaDeDatosActionPerformed(evt);
            }
        });

        SalidaDeDatos.setColumns(20);
        SalidaDeDatos.setRows(5);
        jScrollPane1.setViewportView(SalidaDeDatos);

        LabelIngreso.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LabelIngreso.setForeground(new java.awt.Color(0, 0, 0));
        LabelIngreso.setText("Ingrese los datos:");

        LabelSalida.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LabelSalida.setForeground(new java.awt.Color(0, 0, 0));
        LabelSalida.setText("Salida de datos:");

        javax.swing.GroupLayout PanelAmarilloLayout = new javax.swing.GroupLayout(PanelAmarillo);
        PanelAmarillo.setLayout(PanelAmarilloLayout);
        PanelAmarilloLayout.setHorizontalGroup(
            PanelAmarilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAmarilloLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(EntradaDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addGap(53, 53, 53))
            .addGroup(PanelAmarilloLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(LabelIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelAmarilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAmarilloLayout.createSequentialGroup()
                    .addContainerGap(466, Short.MAX_VALUE)
                    .addComponent(LabelSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(102, 102, 102)))
        );
        PanelAmarilloLayout.setVerticalGroup(
            PanelAmarilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAmarilloLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(LabelIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelAmarilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EntradaDeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(PanelAmarilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelAmarilloLayout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(LabelSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(413, Short.MAX_VALUE)))
        );

        PanelAzul.setBackground(new java.awt.Color(51, 204, 255));

        LabelTitulo.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        LabelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        LabelTitulo.setText("SISTEMA CONTROL ACADEMICO");

        javax.swing.GroupLayout PanelAzulLayout = new javax.swing.GroupLayout(PanelAzul);
        PanelAzul.setLayout(PanelAzulLayout);
        PanelAzulLayout.setHorizontalGroup(
            PanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAzulLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        PanelAzulLayout.setVerticalGroup(
            PanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAzulLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(LabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelVerde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelAmarillo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelAzul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(PanelVerde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelAmarillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAdiDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdiDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAdiDocActionPerformed

    private void BtnListarEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListarEstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnListarEstActionPerformed

    private void BtnListarDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListarDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnListarDocActionPerformed

    private void BtnAdiEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdiEstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAdiEstActionPerformed

    private void EntradaDeDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaDeDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaDeDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PANEL().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdiDoc;
    private javax.swing.JButton BtnAdiEst;
    private javax.swing.JButton BtnListarDoc;
    private javax.swing.JButton BtnListarEst;
    private javax.swing.JTextField EntradaDeDatos;
    private javax.swing.JLabel LabelIngreso;
    private javax.swing.JLabel LabelSalida;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JPanel PanelAmarillo;
    private javax.swing.JPanel PanelAzul;
    private javax.swing.JPanel PanelVerde;
    private javax.swing.JTextArea SalidaDeDatos;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
